export const refs = {
  openMenuBtn: document.querySelector('[data-menu-open]'),
  closeMenuBtn: document.querySelector('[data-menu-close]'),
  menu: document.querySelector('[data-menu]'),
  body: document.querySelector('body'),
  menuList: document.querySelector('.menu-list'),
  openModalBtn: document.querySelector('[data-modal-open]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  modal: document.querySelector('[data-modal]'),
  submitBtn: document.querySelector('[data-submit]'),
  form: document.querySelector('.modal-form'),
  checkbox: document.querySelector('.modal-form__checkbox'),
  checkboxIcon: document.querySelector('.modal-form__checkbox-icon'),
  filter: document.querySelector('[data-filter]'),
  filterAll: document.querySelector('[data-filter-all]'),
  filterWeb: document.querySelector('[data-filter-web]'),
  filterApp: document.querySelector('[data-filter-app]'),
  filterDesign: document.querySelector('[data-filter-design]'),
  filterMarketing: document.querySelector('[data-filter-marketing]'),
};
